# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testurl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='url_name',
        ),
        migrations.AddField(
            model_name='check',
            name='http_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='short_id',
            field=models.SlugField(blank=True, max_length=6, null=True),
        ),
    ]
