# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testurl', '0002_auto_20171227_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='short_id',
            field=models.SlugField(blank=True, max_length=9, null=True),
        ),
    ]
