# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testurl', '0004_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
