# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testurl', '0005_delete_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='short_id',
            field=models.SlugField(blank=True, max_length=7, null=True),
        ),
    ]
